; generated by Component: ARM Compiler 5.06 update 1 (build 61) Tool: ArmCC [4d35ad]
; commandline ArmCC [--c99 --split_sections --debug -c -S -ouacpymark\uacpy.s --depend=uacpymark\uacpy.d --cpu=Cortex-M3 --apcs=interwork -O3 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -ID:\works\stm3210e-lk\uacpymark\MDK-ARM\RTE -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\4.5.0\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F1xx_DFP\2.1.0\Device\Include -D__MICROLIB -D__UVISION_VERSION=517 -D_RTE_ -DSTM32F10X_HD -DUSE_HAL_DRIVER -DSTM32F103xE --omf_browse=uacpymark\uacpy.crf ..\Src\uacpy.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.uacpy||, CODE, READONLY, ALIGN=1

uacpy PROC
	TST	R0, #3
	BEQ	__acpy4

	PUSH	{R0, R4, R5, R6, R7, LR}

	CMP	R2, #4
        POPLT	{R0, R4, R5, R6, R7, LR}
	

	SUB	R1, R1, R0
	ADD	R2, R0, R1
__uacpy
	AND	R4, R0, #3
	CMP	R4, #2
; 1
	LDRLTB	R3, [R0, R1]
	STRLTB	R3, [R0]
	ADDLT	R0, #1
; 1, 2
	LDRLEH	R3, [R0, R1]
	STRLEH	R3, [R0]
	ADDLE	R0, #2
;3
	LDRGTB	R3, [R0, R1]
	STRGTB	R3, [R0]
	ADDGT	R0, #1


	TST	R0, #3
__bug__
	BNE	__bug__


__cpy4
	AND	R6, R1, #3	;R0 已经对齐了
	BIC	R1, #3

	LSL	R6, #3
	MOV	R7, #32
	SUB	R7, R7, R6

	LDR	R5, [R0]
	LSL	R5, R5, R6
	LSR	R5, R5, R6
__0cpy
	LDR	R3, [R0, R1]
	LSR	R4, R3, R7
	ORR	R4, R5
	STR	R4, [R0]
	LSL	R5, R3, R6
	
	ADD	R0, #4
	CMP	R0, R2
	BLE	__0cpy	; 多复制了差不多一个
	

	


        POP	{R0, R4, R5, R6, R7, LR}
__acpy4
	
	BX	LR
lz4data
	INCBIN	memory-barriers.txt.lz4
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT uacpy [CODE]
	EXPORT lz4data [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
